base_url = "https://tmbu.ericscouten.com"

title = "This Might Be Useful"
description = "A linkroll of things I've found that might be useful someday."
default_language = "en"

theme = "zola-es-theme"

compile_sass = true
build_search_index = true

generate_feed = true
feed_filename = "rss.xml"

[markdown]
highlight_code = true
smart_punctuation = true

[extra]
hashtags = "#linkroll #tech #photography"
endmark = true
es_site = "tmbu"
map_clustering = false
is_dark = true

[[taxonomies]]
name = "tag"

[extra.taxonomies.tag]
title = "Tags"
sort = "date"
